name: books
services:
  frontend:
    image: okteto.dev/frontend
    build: frontend
    ports:
    - 8080
  gateway:
    image: okteto.dev/graphql-gateway
    build: gateway
    ports:
    - 4000
  service:
    image: okteto.dev/graphql-service
    build: service
    ports:
    - 4001
endpoints:
  - path: /
    service: frontend
    port: 8080
  - path: /graphql
    service: gateway
    port: 4000